In [157]:
import numpy as np
# A = np.random.randint(9,size=(4,4))

In [158]:
A=[[41,67,34,0,69],
  [24,78,58,62,64],
  [5,45,81,27,61],
  [91,95,42,27,36],
  [91,4,2,53,92]]

In [249]:
class Solution:
    def minFallingPathSum(self, A):
        r, c = len(A), len(A[0])
        P=np.random.randint(998,999,(r - 1, c))        
        newrow = np.zeros(len(A))
        P=np.vstack([P,newrow])
          
        for row in range(r-2 , -1, -1):
            for col in range(c-1,-1,-1):
                if col == 0:
                    P[row][col] = min(abs(A[row+1][col]-A[row][col])+P[row+1][col], 
                                      abs(A[row+1][col+1]-A[row][col])+P[row+1][col + 1])                    
                elif col == c - 1:
                    P[row][col] = min(abs(A[row+1][col-1]-A[row][col])+P[row+1][col-1], 
                                      abs(A[row+1][col]-A[row][col])+P[row+1][col])                    
                else:
                    P[row][col] = min(abs(A[row + 1][col-1]-A[row][col])+P[row + 1][col-1],
                                      abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1],
                                      abs(A[row+1][col]-A[row][col])+P[row+1][col])                    
                #print(row,col)                
                #print(P)
        return min(P[0])

import numpy as np
A = np.random.randint(9,size=(4,4))
# A=[[41,67,34,0,69],
#   [24,78,58,62,64],
#   [5,45,81,27,61],
#   [91,95,42,27,36],
#   [91,4,2,53,92]]
wang=Solution()
wang.minFallingPathSum(A)

7.0

array([[6, 0, 1, 3],
       [4, 5, 7, 8],
       [1, 8, 6, 8],
       [5, 7, 4, 1]])

In [247]:

class Solution:
    def minFallingPathSum(self, A):
        r, c = len(A), len(A[0])
        P=np.random.randint(998,999,(r - 1, c))
#         W=np.zeros((r,c), dtype = np.string_)
        B=[]
        for i in range(0,r*c):
            B.append("")
        W = np.reshape(B,(r,c))
        
        newrow = np.zeros(len(A))
        P=np.vstack([P,newrow])
        for row in range(r-2 , -1, -1):
            for col in range(c-1,-1,-1):
                if col == 0:
                    P[row][col] = min(abs(A[row+1][col]-A[row][col])+P[row+1][col], 
                                      abs(A[row+1][col + 1]-A[row][col]) + P[row+1][col + 1])  
                    if((abs(A[row+1][col]-A[row][col])+P[row+1][col] < abs(A[row+1][col + 1]-A[row][col]) + P[row+1][col + 1])):
                                      W[row][col] = W[row + 1][col] + str(col)
                    else: 
                                      W[row][col] = W[row + 1][col + 1] + str(col + 1)                
                elif col == c - 1:
                    P[row][col] = min(abs(A[row + 1][col-1]-A[row][col])+P[row + 1][col-1], 
                                      abs(A[row+1][col]-A[row][col])+P[row+1][col]) 
                    if((abs(A[row + 1][col-1]-A[row][col])+P[row + 1][col-1] < abs(A[row+1][col]-A[row][col])+P[row+1][col])):
                                      W[row][col] = W[row + 1][col - 1] + str(col - 1)
                    else: 
                                      W[row][col] = W[row + 1][col] + str(col);                   
                else:
                    P[row][col] = min(abs(A[row + 1][col]-A[row][col])+P[row + 1][col],
                                      abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1],
                                      abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1])
                    if((abs(A[row + 1][col]-A[row][col])+P[row + 1][col] < abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1]) and 
                       (abs(A[row + 1][col]-A[row][col])+P[row + 1][col] < abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1])):
                                      W[row][col] = W[row + 1][col] + str(col)
                    elif((abs(A[row + 1][col + 1]-A[row][col])+P[row + 1][col + 1] < abs(A[row+1][col]-A[row][col])+P[row+1][col]) and 
                         (abs(A[row + 1][col + 1]-A[row][col])+P[row + 1][col + 1] < abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1])): 
                                      W[row][col] = W[row + 1][col + 1] + str(col + 1)  
                    else:     
                                      W[row][col] = W[row + 1][col - 1] + str(col - 1)              
                #print(row,col)                
                print(P)
                print(W)
        return min(P[0])

import numpy as np
A=[[41,67,34,0,69],
  [24,78,58,62,64],
  [5,45,81,27,61],
  [91,95,42,27,36],
  [91,4,2,53,92]]
wang=Solution()
wang.minFallingPathSum(A)

[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998.  17.]
 [  0.   0.   0.   0.   0.]]
[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '3']
 ['' '' '' '' '']]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998.  25.  17.]
 [  0.   0.   0.   0.   0.]]
[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '2' '3']
 ['' '' '' '' '']]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998.  11.  25.  17.]
 [  0.   0.   0.   0.   0.]]
[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '3' '2' '3']
 ['' '' '' '' '']]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998.   4.  11.  25.  17.]
 [  0.   0.   0.   0.   0.]]
[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '0' '3' '2' '3']
 ['' '' '' '' '']]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998.

32.0

In [252]:
class Solution:
    def minFallingPathSum(self, A):
        r, c = len(A), len(A[0])
        P=np.random.randint(998,999,(r - 1, c))       
        newrow = np.zeros(len(A))
        P=np.vstack([P,newrow])
        Q=P
        for row in range(r-2 , -1, -1):
            for col in range(c-1,-1,-1):
                if col == 0:
                    P[row][col] = min(abs(A[row+1][col]-A[row][col])+P[row+1][col],
                                      abs(A[row+1][col + 1]-A[row][col]) + P[row+1][col + 1]) 
                    if abs(A[row+1][col]-A[row][col])+P[row+1][col] < abs(A[row+1][col + 1]-A[row][col]) + P[row+1][col + 1]:
                        Q[row][col] = Q[row+1][col]*10 + col
                    else:
                        Q[row][col] = Q[row+1][col+1]*10 + col + 1
                elif col == c - 1:
                    P[row][col] = min(abs(A[row + 1][col-1]-A[row][col])+P[row + 1][col-1],
                                      abs(A[row+1][col]-A[row][col])+P[row+1][col]) 
                    if abs(A[row + 1][col-1]-A[row][col])+P[row + 1][col-1] > abs(A[row+1][col]-A[row][col])+P[row+1][col]:
                        Q[row][col] = Q[row+1][col]*10 + col
                    else:
                        Q[row][col] = Q[row+1][col-1]*10 + col - 1                  
                else:
                    P[row][col] = min(abs(A[row + 1][col]-A[row][col])+P[row + 1][col],
                                      abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1],
                                      abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1])                   
                    if ((abs(A[row + 1][col]-A[row][col])+P[row + 1][col] < abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1]) and (A[row + 1][col]-A[row][col])+P[row + 1][col] < abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1]):
                        Q[row][col] = Q[row + 1][col]*10 + col
                    elif ((abs(A[row + 1][col]-A[row][col])+P[row + 1][col] > abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1]) and (A[row + 1][col + 1]-A[row][col])+P[row + 1][col + 1] < abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1]):
                        Q[row][col] = Q[row + 1][col + 1]*10 + col + 1
                    else:
                        Q[row][col] = Q[row + 1][col - 1]*10 + col - 1
                #print(row,col)               
                print(P)
        return P[0]

import numpy as np
A=[[41,67,34,0,69],
  [24,78,58,62,64],
  [5,45,81,27,61],
  [91,95,42,27,36],
  [91,4,2,53,92]]
wang=Solution()
wang.minFallingPathSum(A)

[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998.   1.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [  0.   1.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998.  34.]
 [  0.   1.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998.  23.  34.]
 [  0.   1.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 9

array([   0.,    0., 2332., 2332., 3444.])

In [246]:
A=[[41,67,34,0,69],
  [24,78,58,62,64],
  [5,45,81,27,61],
  [91,95,42,27,36],
  [91,4,2,53,92]]
wang=Solution()
wang.minFallingPathSum(A)
        

[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998.   1.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [  0.   1.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998. 998.  34.]
 [  0.   1.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 998. 998. 998.]
 [998. 998. 998. 998. 998.]
 [998. 998. 998.  23.  34.]
 [  0.   1.   3.   2.   3.]
 [  0.   0.   0.   0.   0.]]
[[998. 998. 9

array([   0.,    0., 2332., 2332., 3444.])

In [263]:
class Solution:
    def minFallingPathSum(self, A):
        r, c = len(A), len(A[0])
        P=np.random.randint(998,999,(r - 1, c))   
        Q=np.random.randint(998,999,(r - 1, c)) 
        newrow = np.zeros(len(A))
        newrow2 = np.array([0,1,2,3,4])#len(c)
        P=np.vstack([P,newrow])
        Q=np.vstack([Q,newrow2])
        for row in range(r-2 , -1, -1):
            for col in range(c-1,-1,-1):
                if col == 0:
                    P[row][col] = min(abs(A[row+1][col]-A[row][col])+P[row+1][col],
                                      abs(A[row+1][col + 1]-A[row][col]) + P[row+1][col + 1]) 
                    if abs(A[row+1][col]-A[row][col])+P[row+1][col] < abs(A[row+1][col + 1]-A[row][col]) + P[row+1][col + 1]:
                        Q[row][col] = Q[row+1][col]*10 + col
                    else:
                        Q[row][col] = Q[row+1][col+1]*10 + col + 1
                elif col == c - 1:
                    P[row][col] = min(abs(A[row + 1][col-1]-A[row][col])+P[row + 1][col-1],
                                      abs(A[row+1][col]-A[row][col])+P[row+1][col]) 
                    if abs(A[row + 1][col-1]-A[row][col])+P[row + 1][col-1] > abs(A[row+1][col]-A[row][col])+P[row+1][col]:
                        Q[row][col] = Q[row+1][col]*10 + col
                    else:
                        Q[row][col] = Q[row+1][col-1]*10 + col - 1                  
                else:
                    P[row][col] = min(abs(A[row + 1][col]-A[row][col])+P[row + 1][col],
                                      abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1],
                                      abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1])                   
                    if (abs(A[row + 1][col]-A[row][col])+P[row + 1][col]<abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1]) and (abs(A[row + 1][col]-A[row][col])+P[row + 1][col]<abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1]):
                        Q[row][col] = Q[row + 1][col]*10 + col
                    elif (abs(A[row + 1][col]-A[row][col])+P[row + 1][col]>abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1]) and (abs(A[row + 1][col + 1]-A[row][col])+P[row + 1][col + 1]<abs(A[row+1][col - 1]-A[row][col])+P[row+1][col - 1]):
                        Q[row][col] = Q[row + 1][col + 1]*10 + col + 1
                    else:
                        Q[row][col] = Q[row + 1][col - 1]*10 + col - 1
                #print(row,col)               
                #print(P)
                #print(Q)
        return min(P[0]),Q
    

import numpy as np
np.set_printoptions(suppress=True)
A=[[41,67,34,0,69],
  [24,78,58,62,64],
  [5,45,81,27,61],
  [91,95,42,27,36],
  [91,4,2,53,92]]
wang=Solution()
wang.minFallingPathSum(A)

[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998 998  33]
 [  0   1   2   3   4]]
[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998  22  33]
 [  0   1   2   3   4]]
[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998 998 998]
 [998 998  33  22  33]
 [  0   1   2   3   4]]
[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998 998 998]
 [998   0  33  22  33]
 [  0   1   2   3   4]]
[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998 998 998]
 [  0   0  33  22  33]
 [  0   1   2   3   4]]
[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998 998 334]
 [  0   0  33  22  33]
 [  0   1   2   3   4]]
[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 998 998 223 334]
 [  0   0  33  22  33]
 [  0   1   2   3   4]]
[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 998   1 223 334]
 [  0   0  33  22  33]
 [  0   1   2   3   4]]
[[998 998 998 998 998]
 [998 998 998 998 998]
 [998 332   1 223 334]
 [ 

array([52., 32., 51., 85., 44.])

In [261]:
c=np.array([1,2,3,4])