In [1]:
import numpy as np
sample3 = np.array([[1, 2, 3, 4, 5],
                   [5, 4, 3, 2, 1],
                   [1, 3, 2, 5, 4],
                   [1, 2, 1, 5, 3],
                   [2, 5, 4, 3, 1]])
def minPath(A):
        r, c = len(A), len(A[0])
        P=np.random.randint(998,999,(r - 1, c))       
        newrow = np.zeros(len(A))
        P=np.vstack([P,newrow])
         
        for row in range(r-2 , -1, -1):
            for col in range(c-1,-1,-1):
                if col == 0:
                    P[row][col] = min(abs(A[row+1][col]-A[row][col])+P[row+1][col],
                                      abs(A[row+1][col+1]-A[row][col])+P[row+1][col + 1])                   
                elif col == c - 1:
                    P[row][col] = min(abs(A[row+1][col-1]-A[row][col])+P[row+1][col-1],
                                      abs(A[row+1][col]-A[row][col])+P[row+1][col])                   
                else:
                    P[row][col] = min(abs(A[row + 1][col-1]-A[row][col])+P[row + 1][col-1],
                                      abs(A[row+1][col + 1]-A[row][col])+P[row+1][col + 1],
                                      abs(A[row+1][col]-A[row][col])+P[row+1][col])                   
        return min(P[0]),P

def print_path(A,weighted_matrix):
    c=len(A)
    node_i,node_j = 0,np.argmin(weighted_matrix[0])
    route=[]
    route.append((node_i,node_j))
    route.append((node_i+1,node_j))
    for i in range(len(A)-2):
        if i ==0:
            row = node_i+1
            col = node_j
        else:
            row=x_path
            col=y_path
        
        #print(row,col)
        if col == 0:
            min_path = min(abs(A[row+1][col]-A[row][col])+weighted_matrix[row+1][col],
                              abs(A[row+1][col+1]-A[row][col])+weighted_matrix[row+1][col + 1])
            print(min_path)
            if min_path==abs(A[row+1][col]-A[row][col])+weighted_matrix[row+1][col]:
                node_j=col
            else:
                node_j=col+1
        elif col == c - 1:
            min_path = min(abs(A[row+1][col-1]-A[row][col])+weighted_matrix[row+1][col-1],
                              abs(A[row+1][col]-A[row][col])+weighted_matrix[row+1][col]) 
            #print(min_path)
            if min_path == abs(A[row+1][col]-A[row][col])+weighted_matrix[row+1][col]:
                node_j=col
            else:
                node_j=col-1

        else:
            min_path = min(abs(A[row + 1][col-1]-A[row][col])+weighted_matrix[row + 1][col-1],
                              abs(A[row+1][col + 1]-A[row][col])+weighted_matrix[row+1][col + 1],
                              abs(A[row+1][col]-A[row][col])+weighted_matrix[row+1][col]) 
            #print(min_path)
            if min_path==abs(A[row + 1][col-1]-A[row][col])+weighted_matrix[row + 1][col-1]:
                node_j = col-1
            elif min_path==abs(A[row+1][col + 1]-A[row][col])+weighted_matrix[row+1][col + 1]:
                node_j = col+1
            else:
                node_j=col

        x_path = row+1
        y_path = node_j

        route.append((x_path,y_path))
    return route
def generate_image_path(A,shortest_path):
    image=np.zeros(A.shape)
    for x in range(len(A)):
        image[shortest_path[x][0],shortest_path[x][1]]=1
    return image
shortest_value,weighted_matrix=minPath(sample3)
print("The shortest value is",shortest_value)
shortest_path = print_path(sample3,weighted_matrix)
print("The shortest path is ",shortest_path)
generateImage= generate_image_path(sample3,shortest_path)
print(generateImage)

The shortest value is 1.0
The shortest path is  [(0, 2), (1, 2), (2, 1), (3, 1), (4, 0)]
[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
